#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  carbonAccounting:

services:
  chaincode-utilityemissions2:
    container_name: chaincode-utilityemissions2.carbonAccounting.com
    image: krybalko/utilityemissions-chaincode:0.0.2
    environment:
      - CHAINCODE_CCID=utilityemissions:0ee431100d9b7ab740c0e72ec86db561b052fd1b9b1e47de198bbabd0954ee97
      - CHAINCODE_ADDRESS=0.0.0.0:9999
    ports:
      - "9999:9999"
