name: Github CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./utility-emissions-channel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Test for utility-emissions-channel
        run: |
          cd ./typescript_app
          npm config set unsafe-perm true
          sudo sh ./runTests.sh --timeout 10000
      - name: Run tests   
        run: |
          cd ./typescript_app
          sudo mocha ./tests --timeout 10000
          
      

      

             
     
 
