name: Github CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./utility-emissions-channel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Test for utility-emissions-channel
        run: |
          cd ./typescript_app
          npm config set unsafe-perm true
          npm config set user root
          id -un
          sudo npm install -g
          sudo npm install -g nodemon
          sudo npm install -g serverless
          sudo npm install -g typescript
          sudo npm install -g mocha
          sudo npm run-script build
          sudo npm run-script start
          sudo mocha ./tests --timeout 10000 
      

             
     
 
