name: Github CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1

      - name: Test for utility-emissions-channel
        run: 
          cd ./utility-emissions-channel/typescript_app
      - name: Run runManual.sh file to start server
        shell: bash
        run: |
          set -x
          ls -l ./runManual.sh
          sh ./runManual.sh
      - name: Run tests
        run: 
          cd tests
          mocha ./tests --timeout 10000
